# Change these first
owner: bitsfdb # Your GitHub organization or username, where this repository lives
repo: RLidentityStatus # The name of this repository

sites:
  - name: RLidentityWeb
    url: https://rlidentity.me
  - name: RLidentityAPI
    url:: api.rlidentity.me/health
    expectedStatusCodes:
     - 200
status-website:  
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rlidentity.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: upptime
  introTitle: "hi there! are all systems **operational** at the moment? "
  introMessage: hey, check us out on our [Discord!](https://rlidentity.me/discord)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  notifications:
    - type: discord
      webhookUrl: $DISCORD_WEBHOOK_URL
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuraton
