# Change these first
owner: bitsfdb 
repo: RLidentityStatus 

sites:
  - name: RLidentityWeb
    url: https://rlidentity.me
  - name: RLidentityAPI
    # fix: removed double colon and added https://
    url: https://api.rlidentity.me/health
    expectedStatusCodes:
      - 200

status-website:  
  cname: status.rlidentity.me
  # baseUrl: /RLidentityStatus
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RLidentity Status
  introTitle: "hi there! are all systems **operational** at the moment? "
  introMessage: hey, check us out on our [Discord!](https://rlidentity.me/discord)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/bitsfdb/RLidentityStatus

# move notifications out of status-website block
notifications:
  - type: discord
    webhookUrl: $DISCORD_WEBHOOK_URL
